### ISSUE TITLE
Which License to pick?

### ISSUE THREAD

**Issue by anton-buyskikh** [Shovan-Physics/cDMRG#4]

**Comment by anton-buyskikh** [comment]
I think MIT template is good enough https://github.com/Shovan-Physics/cDMRG/community/license/new?branch=main&template=mit

@Shovan-Physics take a look at other top suggestions, I don't have strong preference.

**Comment by Shovan-Physics** [comment]
I have no idea of what options we have.. ITensor has some Apache License 2.0 license: https://github.com/ITensor/ITensor/blob/v3/LICENSE

**Comment by Shovan-Physics** [comment]
Is there any clause that if you use ITensor you have to use the same license? What about Mathematica?

Also, we should probably check with Erich before selecting one.

**Comment by anton-buyskikh** [comment]
@Shovan-Physics yes, double check with him.

Regarding ITensor's licence: https://softwareengineering.stackexchange.com/a/262071/349723 says that Apache 2.0 is not transferable to the derived code, i.e. use whatever.

**Comment by Shovan-Physics** [comment]
OK great, I'll check with Erich. It does say "The users of your application must receive a copy of the Apache 2.0 license."

**Comment by Shovan-Physics** [comment]
@anton-buyskikh Let's go with Apache 2.0. I talked with Erich today. Basically, Apache 2.0 and the MIT one should be functionally equivalent for us.
